name: Build OpenWrt ARM Binary

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install zig for cross compile
        run: |
          sudo apt update
          sudo apt install -y zig

      - name: Add musl target
        run: |
          rustup target add armv7-unknown-linux-musleabihf

      - name: Build Release with TLS feature
        env:
          CC_armv7_unknown_linux_musleabihf: "zig cc -target arm-linux-musleabihf -static"
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_MUSLEABIHF_LINKER: "zig cc -target arm-linux-musleabihf -static"
        run: |
          cargo build --release --target armv7-unknown-linux-musleabihf --features "tls"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-arm-binary
          path: target/armv7-unknown-linux-musleabihf/release/*
